server:
  servlet:
    context-path: /api/v1
    
spring:
  autoconfigure.exclude: org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchRestHealthIndicatorAutoConfiguration
  profiles.active: production
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300

elasticsearch:
  transport:
    ping_timeout: 60
    nodes_sampler_interval: 60
  indexes:
    customer: index_customer
  aliases:
    customer: alias_index_customer
  ip: localhost
  port: 9300
  cluster: elasticsearch
  user: elastic
  password: changeme

management.endpoint.health.show-details: ALWAYS
management.health.elasticsearch.indices: index-customer
management.health.elasticsearch.response-timeout: 1000
